#!/usr/bin/python3
"""
    a Python file similar to model_state.py named model_city.py
    that contains the class definition of a City
"""
from relationship_state import Base
from sqlalchemy import Column, Integer, String, ForeignKey


class City(Base):
    """
        Inherits from Base

        Column
            id: unique key, autogenerated. the id of the city
            name: the name of the city
            state_id: the representing the foreign state id
    """
    __tablename__ = "cities"
    id = Column(Integer, nullable=False, unique=True, primary_key=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)
